//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fruit_Ahmed_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart_Component
    {
        public int Cart_ComponentID { get; set; }
        public int Product_ID { get; set; }
        public string quantity { get; set; }
        public string Total_Price { get; set; }
        public Nullable<int> Cart_ID { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Product Product { get; set; }
    }
}
