//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fruit_Ahmed_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class FruitEntities : DbContext
    {
        public FruitEntities()
            : base("name=FruitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cart> Carts { get; set; }
        public DbSet<Cart_Component> Cart_Component { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Citye> Cityes { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Massege> Masseges { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Order_Component> Order_Component { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Quarter> Quarters { get; set; }
        public DbSet<Rate> Rates { get; set; }
    
        public virtual int delecust(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delecust", idParameter);
        }
    
        public virtual int deletecart()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deletecart");
        }
    
        public virtual int DeleteProduct(Nullable<int> product_ID)
        {
            var product_IDParameter = product_ID.HasValue ?
                new ObjectParameter("product_ID", product_ID) :
                new ObjectParameter("product_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProduct", product_IDParameter);
        }
    
        public virtual ObjectResult<SelectFruits_Result> SelectFruits()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectFruits_Result>("SelectFruits");
        }
    
        public virtual ObjectResult<SelectProducts_Result> SelectProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectProducts_Result>("SelectProducts");
        }
    
        public virtual ObjectResult<SelectVegs_Result> SelectVegs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectVegs_Result>("SelectVegs");
        }
    
        public virtual int UpdateProduct(Nullable<int> id, string price, string quantity)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var priceParameter = price != null ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(string));
    
            var quantityParameter = quantity != null ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateProduct", idParameter, priceParameter, quantityParameter);
        }
    
        public virtual ObjectResult<SelectCity1_Result> SelectCity1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectCity1_Result>("SelectCity1");
        }
    
        public virtual ObjectResult<SelectCity2_Result> SelectCity2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectCity2_Result>("SelectCity2");
        }
    
        public virtual ObjectResult<SelectCity3_Result> SelectCity3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectCity3_Result>("SelectCity3");
        }
    }
}
