//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fruit_Ahmed_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Order_Component = new HashSet<Order_Component>();
        }
    
        public int order_ID { get; set; }
        public int customer_ID { get; set; }
        public int CityID { get; set; }
        public System.DateTime driveDate { get; set; }
        public string status { get; set; }
        public string mobile { get; set; }
        public string TotalPrice { get; set; }
        public string OrderNo { get; set; }
        public Nullable<double> longi { get; set; }
        public Nullable<double> lati { get; set; }
        public Nullable<int> QuarterID { get; set; }
    
        public virtual Citye Citye { get; set; }
        public virtual ICollection<Order_Component> Order_Component { get; set; }
        public virtual Quarter Quarter { get; set; }
    }
}
