//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fruit_Ahmed_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quarter
    {
        public Quarter()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int QuarterID { get; set; }
        public int CItyID { get; set; }
        public string QuarterName { get; set; }
    
        public virtual Citye Citye { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
